spring.application.name=jobportal
spring.datasource.url  = jdbc:mysql://localhost:3306/jobportal
spring.datasource.username  = root
spring.datasource.password =
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true
# ===============================
# JWT Configuration
# ===============================
jwt.secret=q7okV6KYIh81sO+NBSyNj/mD8h6mVR/UmmWOUq1nArqWdBap9S/QMshgtO6Wws3vBGeHoQceyNg7uW2ZC1+C/g==
jwt.expiration=86400000